NAME=yourvc
USER=ubuntu

DIR=/opt/$NAME
SERVICE_NAME="${NAME}_bot.service"
SERVICE_FILE_PATH=/etc/systemd/system/$SERVICE_NAME

ENV_PATH=$DIR/env
TTS_PATH=$DIR/TTS
DATA_PATH=$DIR/data

CONFIG_PATH=$DATA_PATH/config.json
MODEL_PATH=$DATA_PATH/best_model.pth.tar
CONFIG_SE_PATH=$DATA_PATH/config_se.json
TTS_SPEAKERS_PATH=$DATA_PATH/speakers.json
TTS_LANGUAGES_PATH=$DATA_PATH/language_ids.json
CHECKPOINT_SE_PATH=$DATA_PATH/SE_checkpoint.pth.tar

REPO_BRANCH='multilingual-torchaudio-SE'
REPO_URL='https://github.com/Edresson/Coqui-TTS'
MODEL_FILE_ID='1sgEjHt0lbPSEw9-FSbC_mBoOPwNi87YR'
CONFIG_FILE_ID='1-PfXD66l1ZpsZmJiC-vhL055CDSugLyP'
CONFIG_SE_FILE_ID='19cDrhZZ0PfKf2Zhr_ebB-QASRw844Tn1'
TTS_SPEAKERS_FILE_ID='1SZ9GE0CBM-xGstiXH2-O2QWdmSXsBKdC'
TTS_LANGUAGES_FILE_ID='1_Vb2_XHqcC0OcvRF82F883MTxfTRmerg'
CHECKPOINT_SE_FILE_ID='17JsW6h6TIh7-LkU2EvB_gnNrPcdBxt7X'